// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yeixcpvhtkutsyqkkmmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllaXhjcHZodGt1dHN5cWtrbW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNzExNjYsImV4cCI6MjA2ODY0NzE2Nn0.s6iX_sHtTprKATZHqByMJ6SXNdBrib1T2g3W4XpVdiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});